Update miner-manager
merge

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -1,12 +1,13 @@
 #!/bin/bash
 
-# to use run `source <(curl -s https://raw.githubusercontent.com/Virosa/third-party-miner-installer-for-ethos/master/miner-manager) miner action` Where the miner is the branch in the repo and the actions are install, update, or revert
-# IE `source <(curl -s https://raw.githubusercontent.com/Virosa/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install`
+# to use run `source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) miner action` Where the miner is the branch in the repo and the actions are install, update, or revert
+# IE `source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/master/miner-manager) phoenixminer install`
 # Any setting changes to this should be made to the miner.settings file in the miners branch of this repo
 
 MINER_BRANCH="$1"
 CMD="$0"
 ACTION="$2"
+VERSION="$3"
 ALLOW="$(cat /opt/ethos/etc/allow.file)"
 
 # Github limits public api requests to 60 per hour, this script does 2 calls per install maxing out at 30 miner installs per hour
@@ -14,19 +15,13 @@ ALLOW="$(cat /opt/ethos/etc/allow.file)"
 # Either install the miner-manager and add a github.com user / pass here
 # or add the two lines to a file /home/ethos/.gituser and you can continue to use the source command or via install. 
 #GITHUB_USERNAME="GitUser"
-#GITHUB_PASSWORD="GitPassword
+#GITHUB_PASSWORD="GitPassword"
 
 # Default miner.settings
 TMP_DIR="/tmp/newminer"
-GIT_USER_REPO="Virosa/third-party-miner-installer-for-ethos"
+GIT_USER_REPO="virosa/third-party-miner-installer-for-ethos"
 #RELEASE_SHASUM="sha256sum of archive"
 #DEPENDS="URL URL"
-
-# Check Github API rate limit
-if [ "$(curl -is https://api.github.com/rate_limit | grep -m1 ^X-RateLimit-Remaining | cut -d : -f 2 | sed 's/\r//g')" -le 2 ] ; then
-  echo "You have installed the maximum number of rigs github allows. You need to wait until $(date -d @"$(curl -is https://api.github.com/rate_limit | grep ^X-RateLimit-Reset: | cut -d : -f 2)" +"%r") or add GitHub authentication."
-  exit 19
-fi
 
 # Assemble API user login
 if [ -f /home/ethos/.gituser ] ; then
@@ -36,16 +31,42 @@ if [ "$GITHUB_PASSWORD" ] ; then
   GIT_LOGIN=" --user $GITHUB_USERNAME:$GITHUB_PASSWORD"
 elif [ "$GITHUB_USERNAME" ] ; then
   GIT_LOGIN=" --user $GITHUB_USERNAME"
+else
+  GIT_LOGIN=""
+fi
+
+# Check Github API rate limit
+if [ "$(curl -is $GIT_LOGIN https://api.github.com/rate_limit | grep -m1 ^X-Ratelimit-Remaining | cut -d : -f 2 | sed 's/\r//g')" -le 2 ] ; then
+  echo "You have installed the maximum number of rigs github allows. You need to wait until $(date -d "@$(curl -is https://api.github.com/rate_limit | grep ^X-Ratelimit-Reset: | cut -d : -f 2)" +%r) or add GitHub authentication."
+  exit 19
 fi
 
 # Get miner files and setup temporary opt/
+if [[ "$MINER_BRANCH" =~ "^ccminer$" ]] ; then 
+  DOWNLOAD_BRANCH="ccminer-tpruvot" 
+else
+  DOWNLOAD_BRANCH="$MINER_BRANCH"
+fi
 f.PREPMINER(){
-  echo "Getting latest release of miner"
-  if [ -z "$DOWNLOAD_URL" ] ; then 
-    DOWNLOAD_URL=$(curl "$GIT_LOGIN" -s "https://api.github.com/repos/$GIT_USER_REPO/releases" \
-    | grep -i "browser_download_url.*$MINER_BRANCH.*t.*z" \
+  if [ -z "$DOWNLOAD_URL" -a -n "$VERSION" ] ; then 
+    echo "Getting version $VERSION of $MINER_BRANCH"
+    DOWNLOAD_URL=$(curl $GIT_LOGIN -s "https://api.github.com/repos/$GIT_USER_REPO/releases" \
+    | grep -i "browser_download_url.*$DOWNLOAD_BRANCH.*t.*z" \
     | cut -d '"' -f 4 \
-    | grep -vE '(osx|txt)' \
+    | grep -vE '(osx|txt|sha256)' \
+    | grep "$VERSION" \
+    | head -1 )
+    if [ -z "$DOWNLOAD_URL" ] ; then 
+      echo "WARNING: Unable to find $MINER_BRANCH version $VERSION. Defaulting to latest version"
+    fi
+  fi
+ 
+  if [ -z "$DOWNLOAD_URL" ] ; then 
+    echo "Getting latest release of miner"
+    DOWNLOAD_URL=$(curl $GIT_LOGIN -s "https://api.github.com/repos/$GIT_USER_REPO/releases" \
+    | grep -i "browser_download_url.*$DOWNLOAD_BRANCH.*t.*z" \
+    | cut -d '"' -f 4 \
+    | grep -vE '(osx|txt|sha256)' \
     | head -1 )
   fi
   COMPRESSION=$(echo "$DOWNLOAD_URL" | grep -oP 't[argxb.]{1,4}z2?$')
@@ -119,7 +140,7 @@ f.PREPETHOS(){
     exit 14
   fi
   echo "Download and unpack files needed by ethOS"
-  if ! git clone https://github.com/Virosa/third-party-miner-installer-for-ethos.git -b "$MINER_BRANCH" ; then
+  if ! git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b "$MINER_BRANCH" ; then
     echo "git clone download failed. Please check your firewall or git access and try again."
     exit 15
   fi 
@@ -169,7 +190,7 @@ f.REVERT(){
     echo "Unable to revert, stock files are not ready for your miner version. Please try \`sudo ethos-update reupdate\`"
     exit 16
   fi
-  if ! git clone https://github.com/Virosa/third-party-miner-installer-for-ethos.git -b ethos ; then
+  if ! git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos ; then
     echo "git clone download failed. Please check your firewall or git access and try again."
     exit 17
   fi 
@@ -215,7 +236,7 @@ f.INSTALL(){
     sed "/#Installed/d" -i /home/ethos/remote.conf
   fi
 
-  if [ "$HOOK_INSTALL" ] ; then $HOOK_INSTALL ; fi
+  if [ "$HOOK_INSTALL" ] ; then ${HOOK_INSTALL[@]} ; fi
 
   echo "Restarting services and miner"
   sudo service ethos-miner-daemon restart
@@ -238,11 +259,11 @@ Usage $CMD [ Miner ] ( install | update | revert )
 Miners Available:
 ${AVAILABLE_MINERS[@]}" | sed -E 's/ +"name": "([a-z0-9\-]+?)", ?/ \1\n/g'
 }
-mapfile -t AVAILABLE_MINERS < <(curl "$GIT_LOGIN" -s https://api.github.com/repos/Virosa/third-party-miner-installer-for-ethos/branches | grep name | grep -Ev '(ethos|master)')
+mapfile -t AVAILABLE_MINERS < <(curl $GIT_LOGIN -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches?per_page=100 | grep name | grep -Ev '(ethos|master)')
 
 # TODO add logging
-if [ "$#" -ne "2" ] ; then
-  f.HELP "Wrong number of arguments, must be 2 arguments miner and action, please refer to https://github.com/Virosa/third-party-miner-installer-for-ethos"
+if [ "$#" -lt "2" -o "$#" -gt "3" ] ; then
+  f.HELP "Wrong number of arguments, must have 2 arguments, a miner and action, please refer to https://github.com/cynixx3/third-party-miner-installer-for-ethos"
   exit 1
 elif ! [[ "${AVAILABLE_MINERS[@]}" == *"\"$MINER_BRANCH\""* ]] ; then
   f.HELP "Invalid miner selected, Please choose from the list below"
@@ -250,7 +271,7 @@ elif ! [[ "${AVAILABLE_MINERS[@]}" == *"\"$MINER_BRANCH\""* ]] ; then
 fi
 
 # Get miner settings
-source <(curl "$GIT_LOGIN" -s "https://raw.githubusercontent.com/Virosa/third-party-miner-installer-for-ethos/$MINER_BRANCH/miner.settings")
+source <(curl $GIT_LOGIN -s "https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/$MINER_BRANCH/miner.settings")
 
 if [ -d "$TMP_DIR" ] ; then rm -rf "$TMP_DIR" ; fi
 echo "Move to a temporary work space"
